export const ENV = {
  STRAVA_CLIENT_ID: process.env.STRAVA_CLIENT_ID!,
  STRAVA_CLIENT_SECRET: process.env.STRAVA_CLIENT_SECRET!,
  STRAVA_VERIFY_TOKEN: process.env.STRAVA_VERIFY_TOKEN!,
  APP_BASE_URL: process.env.APP_BASE_URL!,
  OAUTH_REDIRECT_URL: process.env.OAUTH_REDIRECT_URL!,

  DATABASE_URL: process.env.DATABASE_URL!,
  REDIS_URL: process.env.REDIS_URL!,
  REDIS_TOKEN: process.env.REDIS_TOKEN!,

  RATE_OVERALL_15M: Number(process.env.RATE_OVERALL_15M ?? 200),
  RATE_OVERALL_DAILY: Number(process.env.RATE_OVERALL_DAILY ?? 2000),
  RATE_NONUPLOAD_15M: Number(process.env.RATE_NONUPLOAD_15M ?? 100),
  RATE_NONUPLOAD_DAILY: Number(process.env.RATE_NONUPLOAD_DAILY ?? 1000),
};